#ifndef ARAPUCA_H
#define ARAPUCA_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Current schema version. Incremented only for breaking changes.
 */
#define arapuca_SCHEMA_VERSION 1

/**
 * Fixed port for the proxy bridge TCP listener. The bridge runs
 * inside an isolated network namespace where port conflicts are
 * impossible. Used by both `bridge_env()` and the audit layer.
 */
#define arapuca_BRIDGE_PORT 18080

/**
 * Maximum size (bytes) for a single guest file's content.
 */
#define arapuca_MAX_GUEST_FILE_SIZE (1024 * 1024)

/**
 * Maximum number of write_files entries.
 */
#define arapuca_MAX_GUEST_WRITE_FILES 16

/**
 * Stdin channel (host → guest).
 */
#define arapuca_CHANNEL_STDIN 0

/**
 * Stdout channel (guest → host).
 */
#define arapuca_CHANNEL_STDOUT 1

/**
 * Stderr channel (guest → host).
 */
#define arapuca_CHANNEL_STDERR 2

/**
 * Control channel (bidirectional).
 */
#define arapuca_CHANNEL_CONTROL 3

/**
 * Frame header: 1 byte channel + 4 bytes length.
 */
#define arapuca_FRAME_HEADER_SIZE 5

/**
 * Maximum control message payload (64 KiB).
 */
#define arapuca_MAX_CONTROL_PAYLOAD (64 * 1024)

/**
 * Maximum data frame payload (1 MiB).
 */
#define arapuca_MAX_DATA_PAYLOAD (1024 * 1024)

/**
 * Maximum EXEC JSON payload (64 KiB).
 */
#define arapuca_MAX_EXEC_PAYLOAD (64 * 1024)

/**
 * Nonce size for socket authentication (256-bit).
 */
#define arapuca_NONCE_SIZE 32

/**
 * Default vsock port for the agent.
 */
#define arapuca_AGENT_VSOCK_PORT 1024

/**
 * Maximum concurrent connections per agent.
 */
#define arapuca_MAX_CONNECTIONS 16

/**
 * Maximum concurrent exec sessions per agent.
 */
#define arapuca_MAX_SESSIONS 32

/**
 * Maximum elements in a JSON string array (args, env).
 */
#define arapuca_MAX_ARRAY_ELEMENTS 4096

/**
 * Idle connection timeout in seconds.
 */
#define arapuca_IDLE_TIMEOUT_SECS 30

/**
 * Opaque launch config.
 */
typedef struct arapuca_ArapucaConfig arapuca_ArapucaConfig;

/**
 * Opaque process handle.
 */
typedef struct arapuca_ArapucaProcess arapuca_ArapucaProcess;

/**
 * Opaque profile builder.
 */
typedef struct arapuca_ArapucaProfile arapuca_ArapucaProfile;

/**
 * Opaque sandbox handle (platform-specific, type-erased).
 */
typedef struct arapuca_ArapucaSandbox arapuca_ArapucaSandbox;

typedef struct arapuca_Option_ArapucaAuditCallback arapuca_Option_ArapucaAuditCallback;

/**
 * Resource usage statistics from cgroups v2.
 */
typedef struct arapuca_ArapucaResourceUsage {
    int64_t memory_current_bytes;
    int64_t memory_peak_bytes;
    double cpu_usage_seconds;
    int64_t pid_count;
    int64_t io_read_bytes;
    int64_t io_write_bytes;
} arapuca_ArapucaResourceUsage;

/**
 * Create a new profile builder.
 */
struct arapuca_ArapucaProfile *arapuca_profile_new(void);

/**
 * Add a read-only path to the profile. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `profile` and `path` must be valid pointers.
 */
int32_t arapuca_profile_add_read_path(struct arapuca_ArapucaProfile *profile, const char *path);

/**
 * Add a read-write path to the profile. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `profile` and `path` must be valid pointers.
 */
int32_t arapuca_profile_add_write_path(struct arapuca_ArapucaProfile *profile, const char *path);

/**
 * Set memory limit in MB. Enforced via cgroups v2 `memory.max`
 * on Linux (through the launch path) and RSS polling on macOS.
 * Does NOT set RLIMIT_AS, which would break Go/JVM/.NET runtimes.
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_memory_mb(struct arapuca_ArapucaProfile *profile, uint64_t mb);

/**
 * Set CPU percentage limit.
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_cpu_pct(struct arapuca_ArapucaProfile *profile, uint32_t pct);

/**
 * Set maximum PIDs. Enforced via cgroups v2 `pids.max` on Linux
 * (through the launch path). Does NOT set RLIMIT_NPROC, which is
 * a per-UID system-wide limit that breaks sandboxed workloads.
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_max_pids(struct arapuca_ArapucaProfile *profile, uint32_t pids);

/**
 * Set maximum file size in MB (RLIMIT_FSIZE).
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_max_file_size_mb(struct arapuca_ArapucaProfile *profile, uint64_t mb);

/**
 * Set maximum open file descriptors (RLIMIT_NOFILE).
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_max_open_files(struct arapuca_ArapucaProfile *profile, uint64_t n);

/**
 * Enable/disable network namespace isolation.
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_netns(struct arapuca_ArapucaProfile *profile, bool enabled);

/**
 * Enable DNS query capture inside the network namespace.
 *
 * When enabled alongside netns, the bridge child intercepts DNS
 * queries and emits NetworkBlocked audit events. Requires the
 * serde feature and the wrapper binary with filesystem paths.
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
void arapuca_profile_set_dns_capture(struct arapuca_ArapucaProfile *profile, bool enabled);

/**
 * Set micro-VM isolation on a profile with a distro image source.
 *
 * After this call, launching with this profile creates a VM instead
 * of a process-level sandbox. Requires the `microvm` feature.
 *
 * # Safety
 * `profile` and `distro`/`version` must be valid pointers.
 */
int32_t arapuca_profile_set_isolation_microvm(struct arapuca_ArapucaProfile *profile,
                                              const char *distro,
                                              const char *version,
                                              uint32_t cpus,
                                              uint32_t mem_mb);

/**
 * Set micro-VM isolation on a profile with an explicit image path.
 *
 * # Safety
 * `profile` and `image_path` must be valid pointers.
 */
int32_t arapuca_profile_set_isolation_microvm_path(struct arapuca_ArapucaProfile *profile,
                                                   const char *image_path,
                                                   uint32_t cpus,
                                                   uint32_t mem_mb);

/**
 * Free a profile. Safe to call with NULL.
 *
 * # Safety
 * `profile` must be NULL or a valid pointer from `arapuca_profile_new()`.
 */
void arapuca_profile_free(struct arapuca_ArapucaProfile *profile);

/**
 * Create a new sandbox for the current platform.
 *
 * Returns NULL on error (check `arapuca_last_error()`).
 */
struct arapuca_ArapucaSandbox *arapuca_sandbox_new(void);

/**
 * Check whether cgroups v2 resource limits are available.
 *
 * # Safety
 * `sb` must be a valid pointer.
 */
bool arapuca_sandbox_cgroups_available(const struct arapuca_ArapucaSandbox *sb);

/**
 * Free a sandbox handle. Safe to call with NULL.
 *
 * # Safety
 * `sb` must be NULL or a valid pointer from `arapuca_sandbox_new()`.
 */
void arapuca_sandbox_free(struct arapuca_ArapucaSandbox *sb);

/**
 * Create a new launch config.
 */
struct arapuca_ArapucaConfig *arapuca_config_new(void);

/**
 * Set the profile on a config (clones the profile).
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_config_set_profile(struct arapuca_ArapucaConfig *cfg,
                                   const struct arapuca_ArapucaProfile *profile);

/**
 * Set the task ID on a config.
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_config_set_task_id(struct arapuca_ArapucaConfig *cfg, const char *task_id);

/**
 * Set the phase on a config.
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_config_set_phase(struct arapuca_ArapucaConfig *cfg, const char *phase);

/**
 * Set the socket directory on a config.
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_config_set_socket_dir(struct arapuca_ArapucaConfig *cfg, const char *dir);

/**
 * Set the working directory on a config.
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_config_set_work_dir(struct arapuca_ArapucaConfig *cfg, const char *dir);

/**
 * Set stdin FD on a config. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `cfg` must be a valid pointer.
 */
int32_t arapuca_config_set_stdin_fd(struct arapuca_ArapucaConfig *cfg, int32_t fd);

/**
 * Set stdout FD on a config. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `cfg` must be a valid pointer.
 */
int32_t arapuca_config_set_stdout_fd(struct arapuca_ArapucaConfig *cfg, int32_t fd);

/**
 * Set stderr FD on a config. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `cfg` must be a valid pointer.
 */
int32_t arapuca_config_set_stderr_fd(struct arapuca_ArapucaConfig *cfg, int32_t fd);

/**
 * Set network proxy socket path on a config.
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_config_set_network_proxy(struct arapuca_ArapucaConfig *cfg, const char *path);

/**
 * Add a caller-supplied environment variable to the config.
 *
 * Both key and value are validated (UTF-8, max 4096 bytes each).
 * Dangerous env vars (ARAPUCA_*, LD_*, etc.) are filtered at
 * launch time by the platform launcher, not here.
 *
 * # Safety
 * All pointers must be valid.
 */
int32_t arapuca_config_add_env(struct arapuca_ArapucaConfig *cfg,
                               const char *key,
                               const char *value);

/**
 * Set an audit callback on a config. Requires the `serde` feature.
 *
 * The callback receives JSON-serialized audit events during the
 * sandbox lifecycle. See `ArapucaAuditCallback` for the safety
 * contract.
 *
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `cfg` must be a valid pointer. `cb` must be a valid function pointer.
 * `user_data` must remain valid until `arapuca_process_cleanup()`.
 */
int32_t arapuca_config_set_audit_callback(struct arapuca_ArapucaConfig *cfg,
                                          struct arapuca_Option_ArapucaAuditCallback cb,
                                          void *user_data);

/**
 * Free a config. Safe to call with NULL.
 *
 * # Safety
 * `cfg` must be NULL or a valid pointer from `arapuca_config_new()`.
 */
void arapuca_config_free(struct arapuca_ArapucaConfig *cfg);

/**
 * Launch a sandboxed subprocess.
 *
 * Returns NULL on error (check `arapuca_last_error()`).
 *
 * # Safety
 * All pointers must be valid. `args` must have `args_count` entries.
 * `extra_fds` must have `extra_fds_count` entries (or be NULL if 0).
 */
struct arapuca_ArapucaProcess *arapuca_launch(struct arapuca_ArapucaSandbox *sb,
                                              const struct arapuca_ArapucaConfig *cfg,
                                              const char *cmd,
                                              const char *const *args,
                                              uintptr_t args_count,
                                              const int32_t *extra_fds,
                                              uintptr_t extra_fds_count);

/**
 * Get the PID of a sandboxed process.
 *
 * # Safety
 * `proc` must be a valid pointer.
 */
uint32_t arapuca_process_pid(const struct arapuca_ArapucaProcess *proc);

/**
 * Wait for a sandboxed process to exit.
 *
 * Returns:
 * - `>= 0`: exit code
 * - `< -1`: killed by signal (value = -signal_number)
 * - `-1`: error (check `arapuca_last_error()`)
 *
 * # Safety
 * `proc` must be a valid pointer.
 */
int32_t arapuca_process_wait(struct arapuca_ArapucaProcess *proc);

/**
 * Read resource usage from the process's cgroup.
 *
 * Must be called before `arapuca_process_cleanup()`.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * Both pointers must be valid.
 */
int32_t arapuca_process_resource_stats(const struct arapuca_ArapucaProcess *proc,
                                       struct arapuca_ArapucaResourceUsage *out);

/**
 * Read OOM kill count from the process's cgroup.
 *
 * Must be called before `arapuca_process_cleanup()`.
 *
 * # Safety
 * `proc` must be a valid pointer.
 */
uint32_t arapuca_process_oom_count(const struct arapuca_ArapucaProcess *proc);

/**
 * Clean up the sandbox temp directory and cgroup.
 *
 * Must only be called after `arapuca_process_wait()` returns.
 * Consumes the process — subsequent calls on the same pointer are no-ops.
 *
 * # Safety
 * `proc` must be a valid pointer.
 */
void arapuca_process_cleanup(struct arapuca_ArapucaProcess *proc);

/**
 * Apply sandbox restrictions to the current process. Fail-closed.
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `profile` must be a valid pointer.
 */
int32_t arapuca_apply(const struct arapuca_ArapucaProfile *profile);

/**
 * Create a socket directory (mode 0700, random suffix).
 *
 * Returns a path string. Caller MUST free with `arapuca_free_string()`.
 * Returns NULL on error.
 */
char *arapuca_make_socket_dir(void);

/**
 * Create a temp directory for a task (random suffix).
 *
 * Returns a path string. Caller MUST free with `arapuca_free_string()`.
 * Returns NULL on error.
 *
 * # Safety
 * `task_id` must be a valid null-terminated string.
 */
char *arapuca_make_tmp_dir(const char *task_id);

/**
 * Find the arapuca wrapper binary.
 *
 * Returns the path or NULL if not found.
 * Caller MUST free with `arapuca_free_string()`.
 */
char *arapuca_wrapper_path(void);

/**
 * Enable selfexec mode: `wrapper_path()` returns `current_exe()`.
 *
 * Call before the first launch. Once enabled, the consumer binary
 * acts as its own Landlock/seccomp trampoline — no separate
 * `arapuca` binary is needed.
 */
void arapuca_enable_selfexec_mode(void);

/**
 * Calculate disk usage of a directory in MB.
 *
 * Returns 0 on error or if the path doesn't exist.
 *
 * # Safety
 * `path` must be a valid null-terminated string.
 */
uint64_t arapuca_disk_usage_mb(const char *path);

/**
 * Free a string returned by arapuca.
 *
 * MUST be used instead of `free()` — the string was allocated by
 * Rust's allocator, not the C allocator.
 *
 * # Safety
 * `s` must be NULL or a pointer returned by a arapuca function.
 */
void arapuca_free_string(char *s);

/**
 * Probe the Landlock ABI version. Returns 0 if unavailable.
 */
uint32_t arapuca_landlock_abi_version(void);

/**
 * Probe whether network namespace isolation is available.
 */
bool arapuca_netns_available(void);

/**
 * Get the last error message. Returns NULL if no error.
 *
 * The returned pointer is valid until the next arapuca call on
 * the same thread. Caller must NOT free it.
 */
const char *arapuca_last_error(void);

/**
 * Check whether micro-VM isolation is available on this system.
 *
 * Returns true if KVM and qemu-img are available.
 */
bool arapuca_microvm_available(void);

/**
 * Pull (download and cache) a micro-VM image.
 *
 * Returns the cached image path as a string. Caller MUST free
 * with `arapuca_free_string()`. Returns NULL on error.
 *
 * # Safety
 * `distro` and `version` must be valid null-terminated strings.
 */
char *arapuca_image_pull(const char *distro, const char *version);

/**
 * Entry point called from the C constructor in go-arapuca.
 * The C side has already verified ARAPUCA_WRAPPER=1 AND argv[1]=="--".
 * argc/argv are passed from C (__libc_argc/__libc_argv) to avoid
 * dependency on Rust's std::env::args_os() .init_array ordering.
 *
 * This function never returns — it applies sandbox restrictions
 * and exec-s into the target command, or _exit-s on failure.
 */
void arapuca_handle_selfexec_if_wrapper(int argc, const char *const *argv);

#endif  /* ARAPUCA_H */
